### ISSUE TITLE
Fix qak::timeMillis() for Windows

### ISSUE THREAD

**Issue by badlogic** [badlogic/qak#2]

**Comment by badlydrawnrod** [comment]
If all you need are milliseconds since Windows was started then [timeGetTime()](https://docs.microsoft.com/en-us/windows/win32/api/timeapi/nf-timeapi-timegettime) in `Winmm.lib` will do the trick. It does however wrap every 49.71 days or so.

```cpp
#if defined(_WIN32)
#include <Windows.h>
#pragma comment(lib, "Winmm.lib")
#else
#include <sys/time.h>
#endif
```

```cpp
#if defined(_WIN32)
u8 qak::timeMillis() {
    DWORD now = timeGetTime();
    return static_cast<u8>(now);
}
#else
u8 qak::timeMillis() {
    timeval time;
    gettimeofday(&time, NULL);
    return u8(time.tv_sec) * 1000 + u8(time.tv_usec / 1000);
}
#endif
```

Alternatively, if you're happy to use the C++ standard library, then [std::chrono](https://en.cppreference.com/w/cpp/chrono/system_clock/now) has you covered:
